.github/workflows/on_schedule.yaml
=> Fixing running CI on schedule

renovate.json
Enables automerging PRs created by Renovate. Automerge conditions are:
1. Minor version or patch changes
2. All CI checks pass
=> (Chore) Enabling automerge for Renovate

tests/integration/webui_helper.py
Fixes UPF name in network slice config.
=> (FIX) Fixing upf name in network slice config

.github/workflows/ci_pipeline.yaml, .github/workflows/issues.yaml
- Adds workflow synching issues to JIRA
- Updates the title of issue created if CI fails
=> (Chore) Adding workflow to synch issues to JIRA

.github/variables/dependencies_versions.env, .github/workflows/integration-tests.yaml, tests/integration/fixtures.py, tests/integration/test_integration.py
- Adds COS back to the integration tests
- Simplifies the workflow
=> chore: Adding COS integration to the E2E tests

tests/integration/webui_helper.py
Adds the bitrate unit to the device group config.
- N/A I have made corresponding changes to the documentation
- N/A I have added tests that validate the behaviour of the software
- N/A Any dependent changes have been merged and published in downstream modules
- N/A I have bumped the version of the library
=> fix: Adding DNN bitrate unit

tests/integration/fixtures.py, tests/integration/test_integration.py
Adds simple tests validating accessibility of NMS and 5G Network Overview Grafana dashboard
=> chore: Adding simple tests for NMS and Grafana dashboard

.github/workflows/integration-tests.yaml
=> chore: bump microk8s to v1.29

.github/workflows/ci_pipeline.yaml, terraform/main.tf
- Limit running CI on PR to the `main` branch only
- Use `gnbsim` from the default channel specified by the `gnbsim` base module
=> chore: Pre-release updates

.github/workflows/ci_pipeline.yaml, .github/workflows/issues.yaml
Fixes issues syncing after the integration run
=> fix: Fixing issues synching

.github/workflows/ci_pipeline.yaml, .github/workflows/dependabot_pr.yaml, .github/workflows/issues.yaml
Updates shared workflows version to `v1.0.0`
=> chore: Updating shared workflows version to v1.0.0

.github/workflows/integration-tests.yaml
Adds option to specify branch to checkout for itests
=> chore: Adding option to specify branch to checkout for itests

.github/workflows/integration-tests.yaml, terraform/terraform.tf
Using range for the Terraform Juju provider
=> fix: Using range for the Terraform Juju provider

terraform/terraform.tf
Update TF provider version to >=0.11.0 to support multiple versions
=> chore: Update TF provider version to >=0.11.0

.github/workflows/ci_pipeline.yaml
This PR fixes issue creation for the main branch. Without this fix, the issue will not be created if 1.4 related issue already exists.
=> fix: Adds 'Main -' prefix to the issue name to distinguish from 1.4 issues

.github/workflows/ci_pipeline.yaml
There was a new line added accidentally in the workflow file which was causing creation of multiple issues for the same release.
This PR fixes the step by removing the new line.
=> fix: Fixes step checking for the issue existence

.github/workflows/integration-tests.yaml, tests/integration/test_integration.py
Changes the default runner to Canonical's self-hosted runner
=> chore: Changes the default runner to Canonical's self-hosted runner

.github/workflows/1_4_scheduled_runs.yaml
Fixes GH URL in 1.4 scheduled runs
=> fix: Fixes GH URL in 1.4 scheduled runs

.github/workflows/ci_pipeline.yaml
Fixes issue title to match the search pattern
=> fix: Fixes issue title to match the search pattern

tests/integration/nms_helper.py, tests/integration/test_integration.py
Use the NMS to configure the SD-Core
=> feat: replace webui by NMS charm

tests/integration/nms_helper.py, tests/integration/test_integration.py
Changes the PLMN from 20893 to 00101.
This PR should be merged along with [gNBsim #318](https://github.com/canonical/sdcore-gnbsim-k8s-operator/pull/318)
=> chore: Updates PLMN to 00101

terraform/main.tf, terraform/versions.tf, tests/integration/test_integration.py
Fixes integration tests after the changes in out Terraform modules
=> fix: Updates integration tests after changes in Terraform

.github/workflows/integration-tests.yaml, terraform/integration_tests.auto.tfvars.j2, terraform/main.tf, terraform/variables.tf, tests/integration/juju_helper.py, tests/integration/nms_helper.py, tests/integration/test_integration.py
- Updates tests to use `fiveg_core_gnb` interface
- Improves E2E logs gathering
=> feat: Updates tests to use fiveg_core_gnb interface

.github/renovate.json5
Add renovate configuration that I forgot in the previous PR.
=> chore: Add renovate configuration

.github/workflows/integration-tests.yaml, .gitignore, terraform/main.tf, tests/integration/nms_helper.py, tests/integration/test_integration.py, tox.ini
Backport fiveg-core-gnb integration to v1.5
=> feat: Backport fiveg-core-gnb integration to v1.5

.github/workflows/integration-tests.yaml, tox.ini
Adds UV and installs tox with it in the main branch
=> fix: Adds UV and installs tox with it
