- CODEOWNERS
Adds `renovate-approve` to CODEOWNERS to automatically approve PRs from renovate. Otherwise auto-merge will still be waiting for an approval.
> Adding renovate-approve app to CODEOWNERS

- CODEOWNERS
Removes `renovate-approve` from CODEOWNERS to see if the auto-approve would still work
> Removing renovate-approve from CODEOWNERS

- .github/actions/ec2-github-runner/action.yml
- .github/workflows/integration-tests.yaml
- tests/integration/fixtures.py
- tests/integration/test_integration.py
- Adds a workaround for [this issue](https://github.com/charmed-kubernetes/pytest-operator/issues/116)
- Installs `juju-crashdump` in the test env
> (FIX) Workaround fixing integration tests

- requirements.txt
Pins the version of `pytest-asyncio` to `0.21.1`.
Context: Latest version of `pytest-asyncio` removes `asyncio_event_loop`. This makes integration tests hang forever.
> fix: Pinning pytest-asyncio to 0.21.1

- requirements.txt
Reverts canonical/sdcore-tests#128
> fix: Revert "chore(deps): update dependency pytest-asyncio to v0.23.2"

- tests/integration/fixtures.py
- tests/integration/test_integration.py
Use the renamed bundles and charms following the recent renaming operation.
> chore: Rename bundle and charms following renaming in other projects

- requirements.txt
Pinning `juju` version to 3.3.0.0, which is last working. With 3.3.1.0 tests started failing because of 
```shell
File "/home/ubuntu/github-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/juju/version.py", line 19, in <module>
CLIENT_VERSION = re.search(r'\d+\.\d+\.\d+', open(VERSION_FILE_PATH).read().strip()).group()
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/github-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/VERSION'
```
> fix: Pinnging juju version to latest working

- .github/workflows/integration-tests.yaml
- tests/integration/juju_helper.py
- tests/integration/test_integration.py
This PR contains a bunch of minor changes contributing to stability and troubleshooting possibilities of e2e integration tests.
1. Fixes archiving of the Juju crashdump
2. Adds archiving of the k8s logs for all the SD-Core pods
3. Adds `juju_wait_for_active_idle` after any Juju action is executed
4. Adds 5 sec sleep after applying SD-Core configuration to allow propagation of the config
> chore: E2E tests improvements

- .github/workflows/integration-tests.yaml
As of January, 18th GH enterprise runners doubled their HW spec. After initial tests, they seem to perform better than the Canonical self-hosted runners. 
This PR changes the env for the E2E tests to GH-hosted runners again.
> chore: Replacing Canonical self-hosted runners with GH runners

- CONTRIBUTING.md
- pyproject.toml
- requirements.in
- requirements.txt
- tests/integration/juju_helper.py
- tests/integration/terraform_helper.py
- tests/integration/test_integration.py
- tests/integration/webui_helper.py
- tox.ini
Move to ruff and codespell for linting. `pyproject-flake8` is currently broken on Python 3.12, making development on Noble break.
> chore: Move to codespell and ruff

- .github/workflows/ci_pipeline.yaml
- .github/workflows/dependabot_pr.yaml
- .github/workflows/issues.yaml
We use the release version of CI workflow instead of pointing to main. This prevents updates to the workflow causing the CI to fail here.
> chore: use release version of github workflows

- tests/integration/test_integration.py
This PR adds up to 5 retries for the simulation. 
Simulation runs a single ping only. Any random networking problem will falsely fail the tests. After this change, simulation will have to fail 5 times in a row before we call the run failed.
> chore: Add retries for simulation

- .github/workflows/ci_pipeline.yaml
Apparently the issues created by the `github-actions` user do not trigger the `issue created` event. As a result, the E2E failures are not reported in the backlog.
This PR adds a workaround for this problem - issue sync is called explicitly after issue creation.
> fix: Sync issues in the main pipeline

- terraform/main.tf
The default channel in the root Terraform modules now points to `1.4/beta`, but in the tests, we always want to pick up latest changes.
This PR hardcodes the SD-Core charms channel to `1.4/edge`.
> chore: Hardcoding SD-Core channel to edge

- tests/integration/juju_helper.py
- tests/integration/test_integration.py
After fetching new version of `pydantic-core`, Traefik can't handle LB IP as ingress gateway. This bug is tracked [here](https://github.com/canonical/traefik-k8s-operator/issues/361).
This PR unblocks the E2E tests by removing `traefik` from awaited deployment status check. It also skips the tests which requires Traefik to proxy the endpoints correctly.
> fix: Adds a workaround for Traefik bug

- .github/workflows/integration-tests.yaml
- tests/integration/test_integration.py
Changes the default CI runner to Canonical's self-hosted runner
> chore: Switches to Canonical self-hosted runners

- tests/integration/test_integration.py
Fixes type error when catching exceptions:
`TypeError: catching classes that do not inherit from BaseException is not allowed`
> fix: Fixes type error when catching exceptions

- tests/integration/test_integration.py
Sdcore integrations tests are failing in v1.4 branch. When we check the logs, some applications(NMS, router, traefik) appear in maintenance status when the tests are run. This PR increases the timeout to check the applications status.
> fix: increase timeout value in integration tests

- tests/integration/nms_helper.py
- tests/integration/test_integration.py
After integrating with TLS certificates interface, the NMS is served on https. This PR updates the address used to reach the NMS on the integration tests.
> feat: add TLS integration to the NMS

- .github/workflows/integration-tests.yaml
We decided to use Juju 3.5 and Microk8s 1.31-strict/stable  in SD-Core 1.5 channel. The reason why this PR updates the Juju and Microk8s versions in integration tests.
> chore: Update Juju version to 3.5 and Microk8s 1.31-strict/stable  in integration tests

- tests/integration/juju_helper.py
- tests/integration/nms_helper.py
- tests/integration/test_integration.py
Now that authentication has been added to the NMS K8s charm, the tests here need to authenticate prior to making other API calls (creating network slices, and subscribers).
This PR Depends on the changes in the NMS K8s charm being merged first:
- https://github.com/canonical/sdcore-nms-k8s-operator/pull/359
> chore: authenticate in NMS prior to making other API calls

- terraform/integration_tests.auto.tfvars.j2
- terraform/main.tf
- terraform/variables.tf
- tests/integration/test_integration.py
After changing the default channel in the Terraform modules to `1.5/stable` the E2E tests would test the same thing over and over again. This PR changes the channel to `1.5/edge` to make sure we're testing the latest stuff.
> chore: Uses 1.5/edge for the tests

- .github/workflows/integration-tests.yaml
Bump juju to the latest stable release: 3.6/stable.
> chore: bump juju version to 3.6/stable

- .github/workflows/ci_pipeline.yaml
This change makes the CI trigger only on PR events, and not on push. This will prevent duplicate runs of CI jobs.
> fix: remove duplicate ci jobs

- .github/workflows/ci_pipeline.yaml
- .github/workflows/integration-tests.yaml
- terraform/main.tf
- tests/integration/juju_helper.py
- tests/integration/test_integration.py
- Adds retry around the simulation to eliminate random issues with triggering Juju action
- Adds retry around fetching Grafana dashboard to prevent random connection issues
- Creates Juju models for Core and RAN outside the TF module to prevent random provider failures when creating the models
- Increases time between applying network configuration and starting the simulation to `30s` to give Core time to propagate config properly
- Gathers logs and describes for `kube-system` Pod to improve troubleshooting
With all these changes I was able to get 15 successful runs in a row: https://github.com/canonical/sdcore-tests/actions/runs/13832359090
> chore: Improves stability of the E2E tests

- .github/workflows/integration-tests.yaml
This PR aims to fix the back-off error during juju bootstrap caused by pull limit on Dockerhub.
> fix: limit dockerhub pulls
